import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { 
  MatButtonModule, 
  MatIconModule, 
  MatInputModule, 
  MatFormFieldModule, 
  MatCheckboxModule, 
  MatSidenavModule, 
  MatToolbarModule, 
  MatListModule,
  MatTabsModule,
  MatCardModule,
  MatSelectModule,
  MatProgressSpinnerModule,
  MatDialogModule,
  MatSnackBarModule,
  MatStepperModule,
  MatRadioModule,
  MatMenuModule,
  MatTableModule,
  MatAutocompleteModule,
  MatChipsModule,
  MatGridListModule,
  MatSlideToggleModule,
  MatTooltipModule,
  MatBadgeModule,
  MatButtonToggleModule,
  MatProgressBarModule,
  MatExpansionModule,
  MatSortModule,
} from '@angular/material';

import { MatPaginatorModule } from '@angular/material/paginator';

@NgModule({
  declarations: [],
  imports: [
    CommonModule, 
    MatButtonModule,
    MatIconModule,
    MatInputModule,
    MatFormFieldModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatTabsModule,
    MatCardModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    MatSnackBarModule,
    MatStepperModule,
    MatRadioModule,
    MatMenuModule,
    MatTableModule,
    MatPaginatorModule,
    MatAutocompleteModule,
    MatChipsModule,
    MatGridListModule,
    MatSlideToggleModule,
    MatTooltipModule,
    MatBadgeModule,
    MatButtonToggleModule,
    MatProgressBarModule,
    MatExpansionModule,
    MatSortModule
  ],
  exports: [
    MatButtonModule,
    MatIconModule,
    MatInputModule,
    MatFormFieldModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatTabsModule,
    MatCardModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    MatSnackBarModule,
    MatStepperModule,
    MatRadioModule,
    MatMenuModule,
    MatTableModule,
    MatPaginatorModule,
    MatAutocompleteModule,
    MatChipsModule,
    MatGridListModule,
    MatSlideToggleModule,
    MatTooltipModule,
    MatBadgeModule,
    MatButtonToggleModule,
    MatProgressBarModule,
    MatExpansionModule,
    MatSortModule
  ],
})
export class MaterialModule { }
